# Generated by Django 3.0.8 on 2020-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
