# Generated by Django 3.0.8 on 2020-07-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordername',
        ),
    ]
