# Generated by Django 3.0.8 on 2020-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20200805_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
