# Generated by Django 3.0.8 on 2020-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20200805_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_times',
            field=models.IntegerField(null=True),
        ),
    ]
