# Generated by Django 3.0.8 on 2020-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20200805_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_times',
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times',
            field=models.IntegerField(null=True),
        ),
    ]
