# Generated by Django 3.0.8 on 2020-08-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20200805_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='present_item',
            field=models.IntegerField(default=0),
        ),
    ]
